title: Paper Data Links
description: Information about data used in papers.
theme: jekyll-theme-minimal
github_repo_url: "https://github.com/hdrlhub/paper-data-links/blob/main"
include:
  - "*.json"
  - CONTRIBUTING.md